# Permalinks
permalink: /:title
production_url : https://www.lucazz.me
#relative_permalinks: true
markdown: kramdown
highlighter: rouge
redirects: yes
exclude: [vendor]

# Setup
title:            Lucas do Amaral Saboya
tagline:          That's my page and blog :-)
url:              https://www.lucazz.me
paginate:         20
baseurl:          /
author:
  name:           Lucas do Amaral Saboya
  url:            https://twitter.com/lucazz
  ghurl:          https://github.com/lucazz
  email:          lucas.saboya@gmail.com
ASSET_PATH: /public/

gems:
  - jekyll-redirect-from
  - jekyll-timeago
